### ISSUE TITLE
Cant make symfony snippets work in Spacevim

### ISSUE THREAD

**Issue by mlapai** [algotech/ultisnips-php#26]
Standard PHP snippets work, but cant make Symfony ones to work. Not sure if i supposed to write here or Spacevim, sorry if this is not related to ultisnips.

init.toml:
```
snippet_engine = "ultisnips"
```

myspacevim.vim
```
let g:spacevim_snippet_engine = "ultisnips"
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-b>"
let g:ultisnips_php_scalar_types = 1

```

**Comment by voronkovich** [comment]
@mlapai, the Symfony snippets in this repository are outdated. I would suggest you to use this: [https://github.com/sniphpets/sniphpets-symfony](https://github.com/sniphpets/sniphpets-symfony)
